// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319.JBob.subsystems;

import org.usfirst.frc319.JBob.RobotMap;
import org.usfirst.frc319.JBob.commands.*;
import org.usfirst.frc319.JBob.commands.FuelVac.FuelVacStop;

import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.DoubleSolenoid;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class fuelVac extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon fuelVac = RobotMap.fuelVacfuelVac;
    private final DoubleSolenoid fuelVacPiston = RobotMap.fuelVacfuelPiston;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new FuelVacStop());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void fuelVacDeploy(){
    	
    }
public void fuelVacRetract(){
    	
    }
public void fuelVacIn(double speed){
	fuelVac.set(speed);
}
public void fuelVacOut(double speed){
	fuelVac.set(speed);
}
public void fuelVacStop(){
	fuelVac.set(0);
}


    
}

